export const REQUEST_FACE = "REQUEST_FACE";
export const RECEIVE_FACE = "RECEIVE_FACE";
export const REQUEST_WORLD_LIST = "REQUEST_WORLD_LIST";
export const RECEIVE_WORLD_LIST = "RECEIVE_WORLD_LIST";
export const SELECT_MAJORTRI = "SELECT_MAJORTRI";
