# Generated by Django 2.0.6 on 2019-06-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='owner',
        ),
    ]
