# Generated by Django 2.0.6 on 2019-06-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_auto_20190625_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
