# Generated by Django 2.0.6 on 2019-06-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_auto_20190627_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='top_level_project',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_set_all_levels', to='timetracker.Project'),
            preserve_default=False,
        ),
    ]
