# Generated by Django 2.0.6 on 2019-06-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_auto_20190627_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='top_level_project',
        ),
    ]
