# Generated by Django 2.0.6 on 2018-06-15 04:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField(default=1)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('genfund', models.PositiveIntegerField(default=20000000)),
                ('debt_private', models.PositiveIntegerField(default=250000000)),
                ('debt_wb', models.PositiveIntegerField(default=750000000)),
                ('debt_wbsap', models.PositiveIntegerField(default=0)),
                ('debt_repay_private', models.PositiveIntegerField(default=0, verbose_name='Repay Private Debt')),
                ('debt_repay_wb', models.PositiveIntegerField(default=0, verbose_name='Repay World Bank Debt')),
                ('debt_repay_wbsap', models.PositiveIntegerField(default=0, verbose_name='Repay World Bank SAP Debt')),
                ('debt_new_wbsap', models.PositiveIntegerField(default=0, verbose_name='New World Bank SAP Debt')),
                ('tax_cocoa', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(30, message='Maximum is 30%%.')], verbose_name='Cocoa Tax')),
                ('tax_lower', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(70, message='Maximum is 70%%.')], verbose_name='Income Tax - Lower Bracket')),
                ('tax_upper', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(70, message='Maximum is 70%%.')], verbose_name='Income Tax - Upper Bracket')),
                ('svc_health', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100, message='Maximum is 100%%.')], verbose_name='Healthcare Funding')),
                ('svc_education', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100, message='Maximum is 100%%.')], verbose_name='Education Funding')),
                ('svc_security', models.PositiveSmallIntegerField(default=35, validators=[django.core.validators.MaxValueValidator(100, message='Maximum is 100%%.')], verbose_name='Security Funding')),
                ('land', models.PositiveIntegerField(default=1000)),
                ('start_corn', models.PositiveIntegerField(default=900)),
                ('start_cocoa', models.PositiveIntegerField(default=100)),
                ('corn', models.PositiveIntegerField(default=900)),
                ('cocoa', models.PositiveIntegerField(default=100)),
                ('wbsap_cocoa', models.PositiveIntegerField(default=0)),
                ('landprod', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pesticides', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Cheap'), (2, 'Expensive')], default=0)),
                ('voted_out', models.BooleanField(default=False)),
                ('decapitalized', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deveconsim.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together={('game', 'turn')},
        ),
    ]
