# Generated by Django 2.0.6 on 2019-08-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('yearpublished', models.IntegerField(blank=True, null=True)),
                ('minplayers', models.IntegerField(blank=True, null=True)),
                ('maxplayers', models.IntegerField(blank=True, null=True)),
                ('minplaytime', models.IntegerField(blank=True, null=True)),
                ('maxplaytime', models.IntegerField(blank=True, null=True)),
                ('playingtime', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('bayesaverage', models.FloatField(blank=True, null=True)),
                ('usersrated', models.IntegerField(blank=True, null=True)),
                ('averageweight', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.FloatField(blank=True, null=True)),
                ('factors_json', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bg_rec.BoardGame')),
            ],
        ),
        migrations.CreateModel(
            name='GameNeighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('distance', models.FloatField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_rec.BoardGame')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameneighbor_set_neighbors', to='bg_rec.BoardGame')),
            ],
        ),
    ]
