# Generated by Django 2.0.6 on 2019-10-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gameneighbor',
            options={'ordering': ['game', 'rank']},
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
