# Generated by Django 2.0.6 on 2019-10-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='face',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='face',
            name='world',
        ),
        migrations.AlterUniqueTogether(
            name='majortri',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='face',
        ),
        migrations.AlterUniqueTogether(
            name='minortri',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='minortri',
            name='major_tri',
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='MajorTri',
        ),
        migrations.DeleteModel(
            name='MinorTri',
        ),
        migrations.DeleteModel(
            name='World',
        ),
    ]
