# Generated by Django 2.0.6 on 2019-10-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majortri',
            name='world',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='triworld.World'),
        ),
    ]
