# Generated by Django 2.0.6 on 2019-10-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0004_face_neighbor_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceJSON',
            fields=[
                ('face', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='triworld.Face')),
                ('neighbor_ids', models.TextField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['face'],
            },
        ),
        migrations.RemoveField(
            model_name='face',
            name='neighbor_ids',
        ),
        migrations.AddIndex(
            model_name='facejson',
            index=models.Index(fields=['face'], name='triworld_fa_face_id_1f2e59_idx'),
        ),
    ]
