# Generated by Django 2.0.6 on 2019-10-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0005_auto_20191005_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='facejson',
            name='map',
            field=models.TextField(default='null', editable=False),
        ),
        migrations.AlterField(
            model_name='facejson',
            name='neighbor_ids',
            field=models.TextField(default='null', editable=False),
        ),
    ]
