# Generated by Django 2.0.6 on 2019-10-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0007_auto_20191005_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceext',
            name='face',
        ),
        migrations.AddField(
            model_name='face',
            name='_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='face',
            name='_neigh_left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_left_set', to='triworld.Face'),
        ),
        migrations.AddField(
            model_name='face',
            name='_neigh_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_right_set', to='triworld.Face'),
        ),
        migrations.AddField(
            model_name='face',
            name='_neigh_top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_top_set', to='triworld.Face'),
        ),
        migrations.DeleteModel(
            name='FaceExt',
        ),
    ]
