# Generated by Django 2.0.6 on 2019-10-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0008_auto_20191007_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='majortri',
            name='_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_left_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_right_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_top_set', to='triworld.MajorTri'),
        ),
        migrations.AlterField(
            model_name='world',
            name='minor_dim',
            field=models.PositiveSmallIntegerField(default=9, help_text='Number of minor triangles per major triangle edge.'),
        ),
    ]
