# Generated by Django 2.0.6 on 2019-10-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0009_auto_20191009_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='_neigh_top',
            new_name='_neigh_top_bottom',
        ),
        migrations.RenameField(
            model_name='majortri',
            old_name='_neigh_top',
            new_name='_neigh_top_bottom',
        ),
    ]
