# Generated by Django 2.0.6 on 2019-10-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0010_auto_20191009_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='face',
            options={'ordering': ['world', 'ring', 'ring_i']},
        ),
        migrations.AlterModelOptions(
            name='majortri',
            options={'ordering': ['face', 'i']},
        ),
        migrations.AlterModelOptions(
            name='minortri',
            options={'ordering': ['major_tri', 'i']},
        ),
        migrations.RemoveIndex(
            model_name='face',
            name='triworld_fa_world_i_ee88fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='majortri',
            name='triworld_ma_face_id_ef8fa3_idx',
        ),
        migrations.RemoveIndex(
            model_name='minortri',
            name='triworld_mi_major_t_e23a73_idx',
        ),
        migrations.RenameField(
            model_name='face',
            old_name='face_ring',
            new_name='ring',
        ),
        migrations.RenameField(
            model_name='face',
            old_name='face_index',
            new_name='ring_i',
        ),
        migrations.AddField(
            model_name='face',
            name='_neigh_top_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_top_bot_set', to='triworld.Face'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_top_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_top_bot_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='i',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minortri',
            name='i',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='face',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='majortri',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='minortri',
            unique_together={('major_tri', 'i')},
        ),
        migrations.AddIndex(
            model_name='face',
            index=models.Index(fields=['world', 'ring', 'ring_i'], name='triworld_fa_world_i_eab3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='majortri',
            index=models.Index(fields=['face', 'i'], name='triworld_ma_face_id_266e44_idx'),
        ),
        migrations.AddIndex(
            model_name='minortri',
            index=models.Index(fields=['major_tri', 'i'], name='triworld_mi_major_t_391758_idx'),
        ),
        migrations.RemoveField(
            model_name='face',
            name='_map',
        ),
        migrations.RemoveField(
            model_name='face',
            name='_neigh_top_bottom',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_top_bottom',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='major_col',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='major_row',
        ),
        migrations.RemoveField(
            model_name='minortri',
            name='minor_col',
        ),
        migrations.RemoveField(
            model_name='minortri',
            name='minor_row',
        ),
    ]
