# Generated by Django 2.0.6 on 2019-10-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0011_auto_20191010_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='face',
            unique_together={('world', 'ring', 'ring_i')},
        ),
        migrations.AlterUniqueTogether(
            name='majortri',
            unique_together={('face', 'i')},
        ),
    ]
