# Generated by Django 2.0.6 on 2019-10-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0012_auto_20191010_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_left',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_right',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_top_bot',
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_0_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_120',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_120_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_180',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_180_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_240',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_240_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_300',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_300_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_60',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_60_set', to='triworld.MajorTri'),
        ),
        migrations.AlterField(
            model_name='world',
            name='major_dim',
            field=models.PositiveSmallIntegerField(help_text='Number of major triangles per face edge.'),
        ),
        migrations.AlterField(
            model_name='world',
            name='minor_dim',
            field=models.PositiveSmallIntegerField(help_text='Number of minor triangles per major triangle edge.'),
        ),
    ]
