# Generated by Django 2.0.6 on 2019-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0014_auto_20191015_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='majortri',
            name='ice',
            field=models.BooleanField(default=False),
        ),
    ]
