# Generated by Django 2.0.6 on 2019-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0015_majortri_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='minortri',
            name='ci',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minortri',
            name='ri',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='minortri',
            index=models.Index(fields=['major_tri', 'ri', 'ci'], name='triworld_mi_major_t_e3aaeb_idx'),
        ),
    ]
