# Generated by Django 2.0.6 on 2019-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0016_auto_20191016_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majortri',
            name='_ci',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_ri',
        ),
        migrations.AddField(
            model_name='majortri',
            name='ci',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='majortri',
            name='ri',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
