# Generated by Django 2.0.6 on 2019-10-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0017_auto_20191016_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='majortri',
            name='_neigh_150',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_150_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_210',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_210_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_270',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_270_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_30',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_30_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_330',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_330_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortri',
            name='_neigh_90',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majortri_90_set', to='triworld.MajorTri'),
        ),
    ]
