# Generated by Django 2.0.6 on 2019-10-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0018_auto_20191018_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorTriNeighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_map',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_0',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_120',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_150',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_180',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_210',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_240',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_270',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_30',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_300',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_330',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_60',
        ),
        migrations.RemoveField(
            model_name='majortri',
            name='_neigh_90',
        ),
        migrations.AddField(
            model_name='majortrineighbor',
            name='from_majortri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majortri_from_set', to='triworld.MajorTri'),
        ),
        migrations.AddField(
            model_name='majortrineighbor',
            name='to_majortri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majortri_to_set', to='triworld.MajorTri'),
        ),
    ]
