# Generated by Django 2.0.6 on 2019-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triworld', '0019_auto_20191018_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='majortri',
            name='cached_neighbor_ids',
            field=models.TextField(default='null'),
        ),
    ]
