# Generated by Django 2.0.6 on 2019-03-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_bggplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGGPlayDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bggplay',
            options={'ordering': ['-date', 'game_name']},
        ),
    ]
