# Generated by Django 2.0.6 on 2018-06-15 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import puzzles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('solution', models.CharField(max_length=50)),
                ('puzzle_template', models.TextField()),
                ('fail_template', models.TextField()),
                ('success_template', models.TextField()),
                ('puzzle_file', models.FileField(blank=True, upload_to=puzzles.models.Puzzle.puzzle_path)),
                ('success_image', models.ImageField(blank=True, upload_to=puzzles.models.Puzzle.puzzle_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
