# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('min_ll', models.PositiveIntegerField(default=1, verbose_name='Minimum Leader Level Required to Hire')),
                ('attack', models.PositiveIntegerField(default=0)),
                ('defense', models.PositiveIntegerField(default=0)),
                ('cost_cp', models.PositiveIntegerField(default=1, verbose_name='Cost in Creature Points')),
                ('cost_gold', models.PositiveIntegerField(default=20, verbose_name='Cost in Gold')),
                ('work_gold', models.PositiveIntegerField(default=5, verbose_name='Gold from Working')),
                ('work_exp', models.PositiveIntegerField(default=1, verbose_name='Experience from Working')),
                ('oversee', models.PositiveIntegerField(default=0, verbose_name='Overseeing Capability')),
            ],
        ),
    ]
