# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creature',
        ),
    ]
