# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0003_auto_20180612_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gold',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
