# Generated by Django 2.0.6 on 2018-06-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0003_auto_20180620_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battalion',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battalions', to='mpatrol.Player'),
        ),
    ]
