# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0004_auto_20180612_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battalion',
            options={'ordering': ['battalion_number']},
        ),
        migrations.AlterModelOptions(
            name='battle',
            options={'ordering': ['-battle_date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AlterField(
            model_name='battle',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_set', to='mpatrol.Player'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_set', to='mpatrol.Player'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_set', to='mpatrol.Player'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to='mpatrol.Player'),
        ),
    ]
