# Generated by Django 2.0.6 on 2018-06-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0004_auto_20180624_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['min_ll', 'cost_xp', 'name']},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='level',
        ),
        migrations.AddField(
            model_name='technology',
            name='min_ll',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Min Leader Level'),
        ),
    ]
