# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0005_auto_20180612_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('life', models.PositiveIntegerField()),
                ('cp', models.PositiveIntegerField()),
                ('xp_cost', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
