# Generated by Django 2.0.6 on 2018-06-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0005_auto_20180624_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderlevel',
            old_name='xp_cost',
            new_name='cost_xp',
        ),
    ]
