# Generated by Django 2.0.6 on 2018-06-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0006_auto_20180624_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='mpatrol.Player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
