# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0006_leaderlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderlevel',
            name='cp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderlevel',
            name='life',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderlevel',
            name='xp_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
