# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0007_auto_20180613_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderlevel',
            options={'ordering': ['ll']},
        ),
        migrations.RenameField(
            model_name='leaderlevel',
            old_name='level',
            new_name='ll',
        ),
    ]
