# Generated by Django 2.0.6 on 2018-06-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0007_playerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlog',
            name='action_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerlog',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_logs', to='mpatrol.Player'),
        ),
    ]
