# Generated by Django 2.0.6 on 2018-06-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0009_playerlog_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_action_date',
        ),
    ]
