# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0010_auto_20180613_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('plural_name', models.CharField(max_length=50)),
                ('min_ll', models.PositiveSmallIntegerField(default=1, verbose_name='Min Leader Level')),
                ('attack', models.PositiveSmallIntegerField(default=0)),
                ('defense', models.PositiveSmallIntegerField(default=0)),
                ('cost_cp', models.PositiveSmallIntegerField(default=1, verbose_name='Cost in Creature Points')),
                ('cost_gold', models.PositiveSmallIntegerField(default=20, verbose_name='Cost in Gold')),
                ('work_gold', models.PositiveSmallIntegerField(default=5, verbose_name='Gold from Working')),
                ('work_xp', models.PositiveSmallIntegerField(default=10, verbose_name='Experience from Working')),
                ('oversee', models.PositiveSmallIntegerField(default=0, verbose_name='Overseeing Capability')),
            ],
            options={
                'ordering': ['min_ll', 'cost_cp', 'cost_gold', 'work_gold', 'work_xp'],
            },
        ),
        migrations.RemoveField(
            model_name='battalion',
            name='creature_type',
        ),
        migrations.AddField(
            model_name='battalion',
            name='creature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Creature'),
        ),
    ]
