# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0011_auto_20180613_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cost_gold', models.PositiveSmallIntegerField(default=100)),
                ('cost_xp', models.PositiveSmallIntegerField(default=100)),
                ('effects', models.TextField(blank=True)),
                ('struct_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Structure', verbose_name='Required Structure')),
            ],
            options={
                'ordering': ['cost_gold', 'cost_xp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('cost', models.PositiveSmallIntegerField(default=100)),
                ('tech_req1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_set1', to='mpatrol.Technology', verbose_name='Required Technology 1')),
                ('tech_req2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_set2', to='mpatrol.Technology', verbose_name='Required Technology 2')),
                ('tech_req3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_set3', to='mpatrol.Technology', verbose_name='Required Technology 3')),
            ],
            options={
                'ordering': ['level', 'cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeaponBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('attack_mult', models.FloatField(default=1.0)),
                ('cost_gold', models.PositiveSmallIntegerField(default=1)),
                ('struct_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Structure', verbose_name='Required Structure')),
                ('tech_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Technology', verbose_name='Required Technology')),
            ],
            options={
                'ordering': ['cost_gold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeaponMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('attack_mult', models.FloatField(default=1.0)),
                ('cost_mult', models.FloatField(default=1.0)),
                ('armor', models.PositiveSmallIntegerField(default=1)),
                ('struct_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Structure', verbose_name='Required Structure')),
                ('tech_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Technology', verbose_name='Required Technology')),
            ],
            options={
                'ordering': ['cost_mult', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='battalion',
            name='weapon_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.WeaponBase'),
        ),
        migrations.AlterField(
            model_name='battalion',
            name='weapon_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.WeaponMaterial'),
        ),
        migrations.AddField(
            model_name='structure',
            name='tech_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mpatrol.Technology', verbose_name='Required Technology'),
        ),
    ]
