# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0012_auto_20180613_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='tech_req1',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tech_req2',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='tech_req3',
        ),
        migrations.AddField(
            model_name='technology',
            name='prereq',
            field=models.ManyToManyField(related_name='_technology_prereq_+', to='mpatrol.Technology'),
        ),
    ]
