# Generated by Django 2.0.6 on 2018-06-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0012_auto_20180629_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='static_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
