# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0013_auto_20180613_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='prereq',
            field=models.ManyToManyField(blank=True, null=True, related_name='_technology_prereq_+', to='mpatrol.Technology'),
        ),
    ]
