# Generated by Django 2.0.6 on 2018-07-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0014_auto_20180630_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
