# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0016_auto_20180613_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='prereq',
            field=models.ManyToManyField(blank=True, to='mpatrol.Technology', verbose_name='Prerequisite'),
        ),
    ]
