# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol', '0017_auto_20180613_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='structures',
            field=models.ManyToManyField(blank=True, to='mpatrol.Structure'),
        ),
        migrations.AddField(
            model_name='player',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='mpatrol.Technology'),
        ),
    ]
