# Generated by Django 2.0.6 on 2018-07-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='interest_gold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structure',
            name='interest_xp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
