# Generated by Django 2.0.6 on 2018-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpatrol_api', '0002_auto_20180715_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_interest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
